### ISSUE TITLE
Failed to activate the go-plus package

### ISSUE THREAD

**Issue by yunhailanuxgk** [joefitzgerald/go-plus#1049]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.5
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package 6.1.0

### Stack Trace

Failed to activate the go-plus package

```
At Cannot find module 'atom-babel6-transpiler' from '/Users/wanglong/.atom/packages/go-plus'

Error: Cannot find module 'atom-babel6-transpiler' from '/Users/wanglong/.atom/packages/go-plus'
    at /app.asar/node_modules/resolve/lib/sync.js:43:15)
    at PackageTranspilationRegistry.getTranspilerPath (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:576178)
    at PackageTranspilationRegistry.getCachePath (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:575133)
    at Object.getCachePath (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:574220)
    at compileFileAtPath (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:148361)
    at Object.value [as .js] (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150943)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:1:688212)
    at Package.requireMainModule (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3220564)
    at Package.activateNow (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3208548)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at PackageManager.triggerDeferredActivationHooks (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:382998)
    at activatePromise.Promise.all.then (/private/var/folders/b_/jlpmj7694hb3lhltfgpc_32w0000gn/T/AppTranslocation/49EF3CC5-E539-4DD9-9DC3-99B3DEBC8134/d/Atom.app/Contents/Resources/app/static/<embedded>:11:381749)
```

### Commands

```
```

### Non-Core Packages

```
atom-ctags 5.1.2 
atom-ide-ui 0.13.0 
autocomplete-solidity 0.3.4 
busy-signal 2.0.1 
go-build 0.2.2 
go-debug 1.7.0 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
intentions 1.1.5 
language-ethereum 0.3.9 
linter 2.0.0 
linter-solidity 0.5.0 
linter-solium 0.0.5 
linter-ui-default 1.8.1 
script 3.25.0 
```

**Comment by jment123a** [comment]
1. 安装nodejs，目的是使用npm
2. 打开cmd，cd  用户路径\.atom\packages\go-plus-master
3. npm install --save atom-babel6-transpiler（可能还需要升级某个工具）

1. Install nodejs, the purpose is to use npm
2. cd user path\.atom\packages\go-plus-master
3. npm install --save atom-babel6-transpiler (may also need to upgrade a tool)
