### ISSUE TITLE
Can't install behind a proxy

### ISSUE THREAD

**Issue by hanjos** [joefitzgerald/go-plus#113]
I'm trying to install `go-plus` in my freshly installed Atom, using the corporate wifi but in my personal MacBook. `autocomplete-plus` went without a problem, but installing `go-plus` returns the following error:

```
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/underscore-plus
npm ERR! git clone git://github.com/joefitzgerald/atom-message-panel.git Cloning into bare repository '/Users/humberto/.atom/.node-gyp/.atom/.apm/_git-remotes/git-github-com-joefitzgerald-atom-message-panel-git-2ac45c06'...
npm ERR! git clone git://github.com/joefitzgerald/atom-message-panel.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/joefitzgerald/atom-message-panel.git github.com[0: 192.30.252.129]: errno=Connection refused
npm ERR! Error: Command failed: Cloning into bare repository '/Users/humberto/.atom/.node-gyp/.atom/.apm/_git-remotes/git-github-com-joefitzgerald-atom-message-panel-git-2ac45c06'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Socket.<anonymous> (child_process.js:969:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/humberto/.atom/.apmrc" "install" "/Users/humberto/.atom/.node-gyp/.atom/.apm/go-plus/3.0.11/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /private/var/folders/bj/j2l_b27s7hs6wqr1l9g90bj40000gn/T/apm-install-dir-1141123-2635-50m979
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/underscore-plus
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/bj/j2l_b27s7hs6wqr1l9g90bj40000gn/T/apm-install-dir-1141123-2635-50m979/npm-debug.log
npm ERR! not ok code 0
```

Thing is, I cannot access git:// URLs behind the corporate firewall. [This workaround](https://github.com/npm/npm/issues/5257#issuecomment-60404802) works in the terminal for `npm` and `git`, but not for `apm`, which seems to ignore Git's configuration.

It's an [`apm` issue](https://github.com/atom/apm/issues/106), certainly, but one you could avoid by using `https://` in the `atom-message-panel` dependency instead of `git://` :)

**Comment by joefitzgerald** [comment]
Fixed in `v3.0.12` - I switched the dependency to git+https.
