### ISSUE TITLE
Uncaught TypeError: Cannot read property 'executable' of undefined

### ISSUE THREAD

**Issue by muralimadhu** [joefitzgerald/go-plus#115]
Uncaught TypeError: Cannot read property 'executable' of undefined

**Atom Version**: 0.158.0
**System**: Mac OS X 10.9.4
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.0.11

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/mmurali/.atom/packages/go-plus/lib/goexecutable.coffee:223

TypeError: Cannot read property 'executable' of undefined
  at GoExecutable.module.exports.GoExecutable.current (/Users/mmurali/.atom/packages/go-plus/lib/goexecutable.coffee:223:22)
  at GoExecutable.current (/Users/mmurali/.atom/packages/go-plus/lib/goexecutable.coffee:1:1)
  at Gofmt.module.exports.Gofmt.formatBuffer (/Users/mmurali/.atom/packages/go-plus/lib/gofmt.coffee:51:33)
  at Gofmt.module.exports.Gofmt.formatCurrentBuffer (/Users/mmurali/.atom/packages/go-plus/lib/gofmt.coffee:30:6)
  at atom-workspace.Gofmt.atom.commands.add.golang:gofmt (/Users/mmurali/.atom/packages/go-plus/lib/gofmt.coffee:13:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`.
