### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buildgopath' of undefined

### ISSUE THREAD

**Issue by azr** [joefitzgerald/go-plus#117]
Hello there,

It's me again !

Gopath is set right .
Atom was launched from command line.

**The problem is fixed after relaunching from command line**

Here is the dump from atom :

Uncaught TypeError: Cannot read property 'buildgopath' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.0.11
### Steps To Reproduce

Type Command + P
Run any of goftm/govet
### Stack Trace

```
At /Users/azer/.atom/packages/go-plus/lib/govet.coffee:47

TypeError: Cannot read property 'buildgopath' of undefined
  at Govet.module.exports.Govet.checkBuffer (/Users/azer/.atom/packages/go-plus/lib/govet.coffee:47:16)
  at Govet.module.exports.Govet.checkCurrentBuffer (/Users/azer/.atom/packages/go-plus/lib/govet.coffee:30:6)
  at atom-workspace.Govet.atom.commands.add.golang:govet (/Users/azer/.atom/packages/go-plus/lib/govet.coffee:13:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by phenixrizen** [comment]
I'm still experiencing this issue

**Comment by joefitzgerald** [comment]
Update your version of atom.

**Comment by mikeys** [comment]
Experiencing the same issue with the latest Atom: 0.188.0

**Comment by joefitzgerald** [comment]
> The problem is fixed after relaunching from command line.

Launch from the command line. https://github.com/joefitzgerald/go-plus#gopath:

> The most common reason GOPATH might not be set in the environment is due to the way OS X launches processes. When you launch Atom via processes created by launchd (e.g. using Finder, the Dock, or Spotlight) it likely will not have access to your $GOPATH if you set it in your shell initialization files (e.g. .bash_profile, .bashrc, .zshrc, etc).

**Comment by mikeys** [comment]
```bash
$ which go
/usr/local/bin/go
$ atom .
```

Packages => Go Plus => Get Missing Tools:
No Go Installations Were found

Am I doing something wrong?

**Comment by joefitzgerald** [comment]
Can you paste your user config for `go-plus`:

`Atom > Open Your Config`, then copy the portion for the key `"go-plus"`.

**Comment by joefitzgerald** [comment]
Also, what version of `go` do you have installed?

```
$ go version
go version go1.4.2 darwin/amd64
```

**Comment by joefitzgerald** [comment]
Finally, please paste the output of `go env`.

**Comment by mikeys** [comment]
Atom Config:
```json
  "go-plus":
    goPath: "~/Development/go"
```

Go version:
```bash
$ go version
go version go1.4.1 darwin/amd64
```

**Comment by mikeys** [comment]
```bash
$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mikey/Development/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by joefitzgerald** [comment]
OK, delete your `goPath` configuration key in the Atom config and save it. You might also want to consider upgrading to `1.4.2` but that shouldn't be necessary.

**Comment by mikeys** [comment]
Restarted atom (from shell) just to be on the safe side after removing the setting from the config file and saving it... still experiencing the same thing

**Comment by joefitzgerald** [comment]
Can you paste the output from `Packages > Go Plus > Display Go Information`?

**Comment by mikeys** [comment]
Just tried it, I get nothing back...

**Comment by mikeys** [comment]
Upgraded to 1.4.2 through brew, still no go :(

**Comment by joefitzgerald** [comment]
Can you open up the inspector (command-option-i) and let me know if there are any errors in the `Console`?

**Comment by joefitzgerald** [comment]
Also @mikeys it might be more productive to join https://gitter.im/joefitzgerald/go-plus, so we can work through this interactively :smile:.

**Comment by mikeys** [comment]
```
 Window load time: 1074ms
/Users/mikey/.atom/packages/go-plus/lib/goexecutable.coffee:154 go [/usr/local/opt/go] is not a valid go
/Users/mikey/.atom/packages/go-plus/lib/gofmt.coffee:84 Uncaught TypeError: Cannot read property 'buildgopath' of undefined
```

I can see it's trying to use `/usr/local/opt/go`, any chance it's trying to use this directory first?

**Comment by joefitzgerald** [comment]
Yep, most likely `/usr/local/opt` is in your path, prior to `/usr/local/bin`. This is blocking the use of the correct go. This is a bug, and is represented in #149. I really need to fix this.
