### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isValidEditor' of null

### ISSUE THREAD

**Issue by arashpayan** [joefitzgerald/go-plus#124]
[Enter steps to reproduce below:]

1. I had a source file from my Go project open
2. In the Atom menu, I clicked Packages -> Go Plus -> Check File Syntax
3. Then the below error popped up and said I should open an issue.

**Atom Version**: 0.165.0
**System**: linux 3.17.1-031701-generic
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.0.13

### Stack Trace

Uncaught TypeError: Cannot read property 'isValidEditor' of null

```
At /home/arash/.atom/packages/go-plus/lib/gobuild.coffee:28

TypeError: Cannot read property 'isValidEditor' of null
  at Gobuild.module.exports.Gobuild.checkCurrentBuffer (/home/arash/.atom/packages/go-plus/lib/gobuild.coffee:28:28)
  at atom-workspace.Gobuild.atom.commands.add.golang:gobuild (/home/arash/.atom/packages/go-plus/lib/gobuild.coffee:16:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -5:44.4 settings-view:open (input.hidden-input)
  2x -5:14.9 symbols-view:toggle-file-symbols (div.markdown-preview.native-key-bindings)
     -3:51.7 core:confirm (input.hidden-input)
     -1:47.8 symbols-view:toggle-project-symbols (input.hidden-input)
     -1:42.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -1:28.8 timecop:view (input.hidden-input)
     -0:48.6 command-palette:toggle (input.hidden-input)
     -0:35.6 golang:updatetools (input.hidden-input)
     -0:00.0 golang:gobuild (input.hidden-input)
```

### Config

```
{
  "core": {
    "useReactEditor": true,
    "disabledPackages": [
      "metrics"
    ],
    "autoHideMenuBar": true
  },
  "go-plus": {}
}
```

### Installed Packages

```coffee
# User
go-plus, v3.0.13
last-cursor-position, v0.6.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by otm** [comment]
I had this issue and I could solve it by updating my go tools

**Comment by arashpayan** [comment]
Yeah, I haven't been able to reproduce it since either, so I'm gonna close this out.
