### ISSUE TITLE
Saving an empty .go file, an error occurred

### ISSUE THREAD

**Issue by kyoh86** [joefitzgerald/go-plus#125]
Uncaught TypeError: Cannot read property '1' of null
/Users/kyoh/.atom/packages/go-plus/lib/gobuild.coffee:68
Hide Stack Trace
TypeError: Cannot read property '1' of null
  at Gobuild.module.exports.Gobuild.checkBuffer (/Users/kyoh/.atom/packages/go-plus/lib/gobuild.coffee:68:27)
  at /Users/kyoh/.atom/packages/go-plus/lib/dispatch.coffee:299:20
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:570:21
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:249:17
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:46:24)
  at async.each (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:124:9)
  at _asyncMap (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:248:13)
  at Object.map (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:219:23)
  at _parallel (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:568:20)
  at Object.async.parallel (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:598:9)
  at /Users/kyoh/.atom/packages/go-plus/lib/dispatch.coffee:291:13
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:254:17
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:157:25
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:251:21
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:615:34
  at /Users/kyoh/.atom/packages/go-plus/lib/gofmt.coffee:73:7
  at exit (/Users/kyoh/.atom/packages/go-plus/lib/executor.coffee:63:7)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:461:12)
The error was thrown from the go-plus package You can help by creating an issue. Please explain what actions triggered this error.

**Comment by joefitzgerald** [comment]
I've seen this error also, I need to add a test and make sure it doesn't cause issues.

**Comment by fourcube** [comment]
Have seen this happen too. It occurs after saving a *.go file. The file contents disappear for half a second and then reappear, with the error message popping up.
