### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by inando** [joefitzgerald/go-plus#153]
I got this error after saving a _test.go file

match = pre.exec(buffer.getText())
testPackage = match[1]   <------

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.1.3

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /C:/Users/roeland/.atom/packages/go-plus/lib/gobuild.coffee:97

TypeError: Cannot read property '1' of null
  at Gobuild.module.exports.Gobuild.checkBuffer (C:\Users\roeland\.atom\packages\go-plus\lib\gobuild.coffee:69:27)
  at C:\Users\roeland\.atom\packages\go-plus\lib\dispatch.coffee:292:20
  at C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:570:21
  at C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:249:17
  at C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:125:13
  at Array.forEach (native)
  at _each (C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:46:24)
  at async.each (C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:124:9)
  at _asyncMap (C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:248:13)
  at Object.map (C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:219:23)
  at _parallel (C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:568:20)
  at Object.async.parallel (C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:598:9)
  at C:\Users\roeland\.atom\packages\go-plus\lib\dispatch.coffee:284:13
  at C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:254:17
  at C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:157:25
  at C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:251:21
  at C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\node_modules\less-cache\node_modules\less\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:615:34
  at C:\Users\roeland\.atom\packages\go-plus\lib\gofmt.coffee:73:7
  at exit (C:\Users\roeland\.atom\packages\go-plus\lib\executor.coffee:64:7)
  at BufferedProcess.triggerExitCallback (C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\src\buffered-process.js:63:47)
  at C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\src\buffered-process.js:70:18
  at Socket.<anonymous> (C:\Users\roeland\AppData\Local\atom\app-0.177.0\resources\app\src\buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:38.0 core:move-up (atom-text-editor.editor.autocomplete-active.is-focused)
  4x -0:36.3 core:move-down (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:34.5 editor:select-to-end-of-line (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:33.4 core:copy (atom-text-editor.editor.autocomplete-active.is-focused)
  3x -0:33.2 core:move-up (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:32.5 core:paste (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:32.0 core:move-down (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:31.4 core:move-up (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:30.7 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
  3x -0:27.9 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:26.1 core:move-down (atom-text-editor.editor.autocomplete-active.is-focused)
  3x -0:25.8 core:select-down (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:25.0 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:24.5 core:save (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:06.2 core:confirm (atom-text-editor.editor.mini)
     -0:04.5 core:save (atom-text-editor.editor.autocomplete-active.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "autoHideMenuBar": true,
    "projectHome": "c:\\dev\\src\\github.com\\inando"
  },
  "go-plus": {
    "goPath": "c:\\dev",
    "goInstallation": "c:\\tools\\go"
  }
}
```

### Installed Packages

```coffee
# User
altgr, v0.1.0
autocomplete-plus, v2.0.12
go-plus, v3.1.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by joefitzgerald** [comment]
Thanks for reporting. This seems related to #125.

**Comment by esiqveland** [comment]
Just got this in OS X. While saving a _test.go file.

Thanks for a great package!

**Atom Version**: 0.177.0
**System**: OS X 10.10.1
**Thrown From**: go-plus package, v3.1.3

```
TypeError: Cannot read property '1' of null
  at Gobuild.module.exports.Gobuild.checkBuffer (/Users/eivindlarsen/.atom/packages/go-plus/lib/gobuild.coffee:69:27)
  at /Users/eivindlarsen/.atom/packages/go-plus/lib/dispatch.coffee:292:20
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:570:21
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:249:17
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:46:24)
  at async.each (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:124:9)
  at _asyncMap (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:248:13)
  at Object.map (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:219:23)
  at _parallel (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:568:20)
  at Object.async.parallel (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:598:9)
  at /Users/eivindlarsen/.atom/packages/go-plus/lib/dispatch.coffee:284:13
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:254:17
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:157:25
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:251:21
  at /Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:615:34
  at /Users/eivindlarsen/.atom/packages/go-plus/lib/gofmt.coffee:73:7
  at exit (/Users/eivindlarsen/.atom/packages/go-plus/lib/executor.coffee:64:7)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)
```
