### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by caiiiyua** [joefitzgerald/go-plus#156]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.180.0
**System**: Mac OS X 10.10
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At /Users/pp/.atom/packages/go-plus/lib/dispatch.coffee:185

TypeError: Cannot read property 'add' of null
  at Dispatch.module.exports.Dispatch.displayGoInfo (/Users/pp/.atom/packages/go-plus/lib/dispatch.coffee:185:20)
  at Dispatch.displayGoInfo (/Users/pp/.atom/packages/go-plus/lib/dispatch.coffee:1:1)
  at /Users/pp/.atom/packages/go-plus/lib/dispatch.coffee:402:8
  at GoExecutable.module.exports.Emitter.emit (/Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at /Users/pp/.atom/packages/go-plus/lib/goexecutable.coffee:218:8
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:254:17
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:157:25
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:251:21
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:615:34
  at done (/Users/pp/.atom/packages/go-plus/lib/goexecutable.coffee:212:11)
  at /Users/pp/.atom/packages/go-plus/lib/goexecutable.coffee:214:11
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:610:21
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:249:17
  at iterate (/Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:149:13)
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:160:25
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:251:21
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:615:34
  at done (/Users/pp/.atom/packages/go-plus/lib/goexecutable.coffee:205:11)
  at exit (/Users/pp/.atom/packages/go-plus/lib/executor.coffee:64:7)
  at BufferedProcess.triggerExitCallback (/Users/pp/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Users/pp/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Users/pp/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -8:27.6 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode)
     -8:11.9 core:confirm (atom-text-editor.editor.mini)
  4x -4:35.3 core:backspace (atom-text-editor.editor.mini)
     -4:32.0 core:confirm (atom-text-editor.editor.mini)
  7x -3:53.6 core:backspace (atom-text-editor.editor.mini)
  2x -3:51.1 core:confirm (atom-text-editor.editor.mini)
  2x -1:12.9 core:paste (atom-text-editor#go-plus.goPath.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "go-plus": {
    "goPath": "/Users/pp/Documents/webdev/godev",
    "goInstallation": "/usr/local/go/bin/go"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.6
go-format, v1.0.7
go-plus, v3.2.2
minimap, v4.2.2
travis-ci-status, v0.11.2
vim-mode, v0.32.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please update `atom` to the latest version (currently `0.187.0) and try again. Please also ensure you're running the latest versions of `autocomplete-plus` and `go-plus`.

I think this may have been an atom issue. `add` is a function from `atom.commands` which should never be undefined unless atom is broken.

**Comment by jensenak** [comment]
Just hit this same error running atom 1.0.2 with go-plus 3.3.12 and autocomplete-plus 2.17.4. OS is Ubuntu 14.04.

Unfortunately, I can't seem to replicate it another time, and everything appears to be working now. This may not need attention, but I just wanted to clarify that an out of date version may not have been the cause of the originally reported error--there may still be a bug in atom.
