### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/glob/glob.js'

### ISSUE THREAD

**Issue by apoydence** [joefitzgerald/go-plus#169]
[Enter steps to reproduce below:]

1. Installed vim-mode
2. Re-opened atom

**Atom Version**: 0.179.0
**System**: Mac OS X 10.9.5
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.3.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/glob/glob.js'

```
At fs.js:570

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/glob/glob.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:136:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/pivotal/.atom/packages/go-plus/lib/gobuild.coffee:3:8)
  at Object.<anonymous> (/Users/pivotal/.atom/packages/go-plus/lib/gobuild.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:74:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/pivotal/.atom/packages/go-plus/lib/dispatch.coffee:6:11)
  at Object.<anonymous> (/Users/pivotal/.atom/packages/go-plus/lib/dispatch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:74:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.module.exports.getDispatch (/Users/pivotal/.atom/packages/go-plus/lib/go-plus.coffee:119:16)
  at Object.<anonymous> (/Users/pivotal/.atom/packages/go-plus/lib/go-plus.coffee:108:8)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.2.0
go-plus, v3.3.0
vim-mode, v0.38.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please update atom and all your packages.
