### ISSUE TITLE
Gocover Uncaught TypeError: Cannot read property 'isValidEditor' of null

### ISSUE THREAD

**Issue by pierrre** [joefitzgerald/go-plus#173]
[Enter steps to reproduce below:]

1. Open a Go file
2. Run gocover
3. It shows an error, but it works

**Atom Version**: 0.187.0
**System**: linux 3.18.6-1-ARCH
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'isValidEditor' of null

```
At /home/pierre/.atom/packages/go-plus/lib/gocover.coffee:104

TypeError: Cannot read property 'isValidEditor' of null
  at Gocover.module.exports.Gocover.runCoverage (/home/pierre/.atom/packages/go-plus/lib/gocover.coffee:104:21)
  at Gocover.runCoverage (/home/pierre/.atom/packages/go-plus/lib/gocover.coffee:1:1)
  at Gocover.module.exports.Gocover.runCoverageForCurrentEditor (/home/pierre/.atom/packages/go-plus/lib/gocover.coffee:101:6)
  at Gocover.runCoverageForCurrentEditor (/home/pierre/.atom/packages/go-plus/lib/gocover.coffee:1:1)
  at atom-workspace.Gocover.atom.commands.add.golang:gocover (/home/pierre/.atom/packages/go-plus/lib/gocover.coffee:25:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:159:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -2:15.5 golang:getmissingtools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:06.4 golang:updatetools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:57.7 window:toggle-dev-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:37.2 core:save (atom-text-editor.editor)
     -1:22.1 editor:newline (atom-text-editor.editor)
     -1:20.5 core:save (atom-text-editor.editor)
     -1:09.5 core:undo (atom-text-editor.editor)
     -1:08.3 core:save (atom-text-editor.editor)
     -1:01.1 editor:newline (atom-text-editor.editor)
     -0:59.6 core:save (atom-text-editor.editor)
  2x -0:47.3 core:backspace (atom-text-editor.editor)
     -0:46.2 core:save (atom-text-editor.editor)
     -0:18.9 golang:cleargocover (atom-text-editor.editor)
     -0:16.5 core:save (atom-text-editor.editor)
     -0:07.6 golang:goinfo (atom-text-editor.editor)
     -0:01.1 golang:gocover (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "go-plus": {
    "goPath": "/home/pierre/Go",
    "goInstallation": "/home/pierre/.gimme/versions/go1.4.2.src/bin/go",
    "runCoverageOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.5.0
file-icons, v1.5.1
go-plus, v3.3.1
minimap, v4.6.0
minimap-selection, v4.2.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by cengizIO** [comment]
I can also replicate this on

**Atom Version:** 0.188.0
**System:** OSX 10.10.2, Kernel Version 14.1.0 x86_64
**Thrown From:** go-plus package, v3.3.2

**Comment by svanharmelen** [comment]
Same here...

Atom Version: 0.189.0
System: OSX 10.9.5
Thrown From: go-plus package, v3.3.5

**Comment by joefitzgerald** [comment]
I am unable to reproduce this issue on `v3.3.10`. I did perform work to prevent this in a prior version (I think `v3.3.5`), but can you please retest? It looks like you were using the menu command or the keyboard shortcut to show test coverage.

**Comment by pierrre** [comment]
It works now on `v3.3.10`.
Thank you!

**Comment by dvirsky** [comment]
Still happens to me in 3.4.1

**Comment by afboteros** [comment]
Still happens to me in 3.4.2 running godef, but godef works.

**Comment by santagada** [comment]
still happens for me.

**Comment by mariusgrigaitis** [comment]
Happens with 3.4.5

**Comment by joefitzgerald** [comment]
Can you please post the actual error contents here if you're still experiencing it? This issue actually contains a number of separate issues and I'd like to isolate where this is currently occurring. Thanks!

**Comment by santagada** [comment]
For me now it is working, it is not scrolling the finding to the top of the screen like I think it should, but it's working.

**Comment by mariusgrigaitis** [comment]
```
/Users/mgrigaitis/.atom/packages/go-plus/lib/godef.coffee:35
Hide Stack Trace
TypeError: Cannot read property 'isValidEditor' of null
  at Godef.module.exports.Godef.gotoDefinitionForWordAtCursor (/Users/mgrigaitis/.atom/packages/go-plus/lib/godef.coffee:35:5)
  at atom-workspace.Godef.atom.commands.add.golang:godef (/Users/mgrigaitis/.atom/packages/go-plus/lib/godef.coffee:14:61)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

**Comment by dahankzter** [comment]
This is unfortunate! One of the neat things was to get tests run on save.

I get the same with 3.5.1 on cover/test from the menu and just silence on save.

**Comment by tehsphinx** [comment]
Same here. All information below

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.5.4


### Stack Trace

Uncaught TypeError: Cannot read property 'isValidEditor' of null

```
At /Users/gn/.atom/packages/go-plus/lib/gocover.coffee:104

TypeError: Cannot read property 'isValidEditor' of null
    at Gocover.module.exports.Gocover.runCoverage (/Users/gn/.atom/packages/go-plus/lib/gocover.coffee:104:21)
    at Gocover.runCoverage (/Users/gn/.atom/packages/go-plus/lib/gocover.coffee:1:1)
    at Gocover.module.exports.Gocover.runCoverageForCurrentEditor (/Users/gn/.atom/packages/go-plus/lib/gocover.coffee:101:6)
    at Gocover.runCoverageForCurrentEditor (/Users/gn/.atom/packages/go-plus/lib/gocover.coffee:1:1)
    at atom-workspace.Gocover.atom.commands.add.golang:gocover (/Users/gn/.atom/packages/go-plus/lib/gocover.coffee:25:29)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -3:40.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:39.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:38 core:backspace (atom-text-editor.editor.is-focused)
     -3:37.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:15.8.0 golang:gocover (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:56.8.0 core:close (div.pane-item.native-key-bindings.about)
     -0:43.6.0 golang:goinfo (atom-text-editor.editor.is-focused)
     -0:27.8.0 golang:updatetools (atom-text-editor.editor.is-focused)
     -0:00.5.0 golang:gocover (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "save-commands"
    ],
    "projectHome": "/Users/gn/go"
  },
  "go-plus": {
    "goPath": "~/go",
    "runCoverageOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v0.2.0
environment, v1.1.1
go-config, v0.3.3
go-get, v0.1.1
go-plus, v3.5.4
go-rename, v0.3.0
gometalinter-linter, v0.1.1
language-docker, v1.1.6
linter, v1.11.3

# Dev
No dev packages
```

**Comment by tehsphinx** [comment]
Seems to work now.

In my case it had to do with the GOPATH not being set correctly for Atom. Starting Atom from the console with the correct GOPATH "fixed" the bug.
