### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by vijayee** [joefitzgerald/go-plus#182]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.13.0-48-generic
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.3.6

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/victor/.atom/packages/go-plus/node_modules/atom-message-panel/lib/LineMessageView.js:51

TypeError: Cannot read property '0' of undefined
  at [object Object].LineMessageView.goToLine (/home/victor/.atom/packages/go-plus/node_modules/atom-message-panel/lib/LineMessageView.js:51:60)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -7:03.5 snippets:expand (input.hidden-input)
     -7:03.4 editor:indent (input.hidden-input)
  5x -6:51.5 core:backspace (input.hidden-input)
     -3:43.9 editor:newline (input.hidden-input)
  2x -3:32.1 core:backspace (input.hidden-input)
  2x -3:27.4 editor:newline (input.hidden-input)
  2x -1:17.7 core:move-left (input.hidden-input)
  2x -1:13.7 core:move-right (input.hidden-input)
  2x -0:57.1 core:backspace (input)
     -0:49.6 core:save (input.hidden-input)
  2x -0:15.6 core:delete (input.hidden-input)
     -0:15.0 core:backspace (input)
  3x -0:13.2 core:move-right (input.hidden-input)
  3x -0:12.2 core:move-left (input.hidden-input)
  3x -0:10.6 core:move-right (input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "graphite-ui",
      "salmon-on-ice-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
go-plus, v3.3.6
graphite-ui, v0.8.2
language-cmake, v0.1.1
salmon-on-ice-syntax, v0.1.1
terminal-panel, v1.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by joefitzgerald** [comment]
Please update your version of Atom. The latest is >= 0.190.0 and you're on 0.165.0.
