### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by acidflip** [joefitzgerald/go-plus#201]
[Enter steps to reproduce below:]

1. Packages > Go Plus > Check File Syntax

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.3.11

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Users/macbookpro/.atom/packages/go-plus/lib/gobuild.coffee:70

TypeError: Cannot read property 'match' of undefined
  at Gobuild.module.exports.Gobuild.checkBuffer (/Users/macbookpro/.atom/packages/go-plus/lib/gobuild.coffee:70:24)
  at Gobuild.module.exports.Gobuild.checkCurrentBuffer (/Users/macbookpro/.atom/packages/go-plus/lib/gobuild.coffee:33:6)
  at atom-workspace.Gobuild.atom.commands.add.golang:gobuild (/Users/macbookpro/.atom/packages/go-plus/lib/gobuild.coffee:17:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:56.9.0 grammar-selector:show (atom-text-editor.editor)
     -0:44.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:43.6.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:42.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:39.7.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:38.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:37.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:37.1.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:36.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:30.9.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:30.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:20.5.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:18.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.1.0 golang:goinfo (atom-text-editor.editor.is-focused)
     -0:01.2.0 golang:gobuild (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-light-theme"
    ]
  },
  "go-plus": {
    "goPath": "$GOPATH/bin"
  }
}
```

### Installed Packages

```coffee
# User
go-plus, v3.3.11

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Your config is wrong. 

```
"go-plus": {
    "goPath": "$GOPATH/bin"
  }
```

Unset that.
