### ISSUE TITLE
Uncaught Error: Cannot find module 'emissary'

### ISSUE THREAD

**Issue by tendertree** [joefitzgerald/go-plus#215]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Windows 8
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.3.12

### Stack Trace

Uncaught Error: Cannot find module 'emissary'

```
At module.js:330

Error: Cannot find module 'emissary'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\gamoonbi\AppData\Local\atom\app-0.211.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\gamoonbi\.atom\packages\go-plus\lib\dispatch.coffee:1:25)
  at Object.<anonymous> (C:\Users\gamoonbi\.atom\packages\go-plus\lib\dispatch.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\gamoonbi\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.getDispatch (C:\Users\gamoonbi\.atom\packages\go-plus\lib\go-plus.coffee:132:16)
  at Object.<anonymous> (C:\Users\gamoonbi\.atom\packages\go-plus\lib\go-plus.coffee:121:8)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
go-plus, v3.3.12
go-runtime, v0.2.0
racer, v0.13.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
`emissary` is no longer used. Please update to `go-plus` `v4.1.0`.
