### ISSUE TITLE
Uncaught SyntaxError: Unexpected token d

### ISSUE THREAD

**Issue by bearclaws73** [joefitzgerald/go-plus#231]
[
func first(x int) (int, bool) {
	if x%2 == 0 {
		return x / 2, true
	} else {
		return x / 2, false
	}
}

func main() {
	x := 71
	y, hx := first(x)
	fmt.Println(y, hx)

}

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.3.12

### Stack Trace

Uncaught SyntaxError: Unexpected token d

```
At file:///C:/Users/yanagic/AppData/Local/atom/app-1.0.0/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22C%3A%5C%5CUsers%5C%5Cyanagic%5C%5CDesktop%5C%5Caccordian.html%22%7D%2C%7B%22pathToOpen%22%3A%22C%3A%5C%5CUsers%5C%5Cyanagic%22%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5Cyanagic%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.0%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Cyanagic%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.0.0%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.0%22%2C%22shellLoadTime%22%3A442%2C%22initialPaths%22%3A%5B%22C%3A%5C%5CUsers%5C%5Cyanagic%5C%5CDesktop%5C%5Caccordian.html%22%2C%22C%3A%5C%5CUsers%5C%5Cyanagic%22%5D%7D:1

SyntaxError: Unexpected token d
    at Object.parse (native)
    at GocodeProvider.module.exports.GocodeProvider.mapMessages (C:\Users\yanagic\.atom\packages\go-plus\lib\gocodeprovider.coffee:131:18)
    at done (C:\Users\yanagic\.atom\packages\go-plus\lib\gocodeprovider.coffee:114:32)
    at exit (C:\Users\yanagic\.atom\packages\go-plus\lib\executor.coffee:105:16)
    at triggerExitCallback (C:\Users\yanagic\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\yanagic\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

### Commands

```
     -2:21.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:16.5.0 core:save (atom-text-editor.editor.is-focused)
 17x -2:10.4.0 core:move-left (atom-text-editor.editor.is-focused)
  6x -1:35.1.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -1:33.4.0 core:delete (atom-text-editor.editor.is-focused)
     -1:30.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:30.1.0 core:delete (atom-text-editor.editor.is-focused)
     -1:28.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:26.8.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:23 core:move-up (atom-text-editor.editor.is-focused)
     -1:19.7.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:18.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:16.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:14.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:42.7.0 core:delete (atom-text-editor.editor.is-focused)
  2x -0:40.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7
go-plus, v3.3.12

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. This is fixed in `autocomplete-go`.
