### ISSUE TITLE
Uncaught TypeError: Cannot read property 'idValidEditor' of null    on godef.coffee:37

### ISSUE THREAD

**Issue by Brasilikum** [joefitzgerald/go-plus#237]
When I tried to use the new "Goto Definition"-Feature, I got the following Error:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'isValidEditor' of null

```
At /Users/georg/.atom/packages/go-plus/lib/godef.coffee:37

TypeError: Cannot read property 'isValidEditor' of null
  at Godef.module.exports.Godef.gotoDefinitionForWordAtCursor (/Users/georg/.atom/packages/go-plus/lib/godef.coffee:37:21)
  at atom-workspace.Godef.atom.commands.add.golang:godef (/Users/georg/.atom/packages/go-plus/lib/godef.coffee:16:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -3:33.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:32.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:32.9.0 tree-view-git-status:toggle (atom-text-editor.editor)
     -3:31.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:26.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:26.1.0 git-plus:commit (atom-text-editor.editor)
 14x -3:14.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:56.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:55.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:53.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:49.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -2:43.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:43.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:43.2.0 git-plus:push (atom-text-editor.editor)
     -1:15.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -0:01.7.0 golang:godef (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "autocomplete-elixir",
      "dash",
      "elixir-cmd",
      "language-docker",
      "language-elixir",
      "linter-elixirc"
    ]
  },
  "go-plus": {
    "goPath": "/Users/georg/go/",
    "environmentOverridesConfiguration": false,
    "runCoverageOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.1
file-icons, v1.5.8
git-plus, v5.2.2
go-plus, v3.4.1
go-rename, v0.3.0
linter-js-yaml, v1.1.1
minimap, v4.11.2
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
This is fixed in `v3.4.5`.
