### ISSUE TITLE
error pop up when opening atom 

### ISSUE THREAD

**Issue by apps4u** [joefitzgerald/go-plus#262]
[Enter steps to reproduce below:]

Open atom via command line in project root run `atom .`

**Atom Version**: 1.0.7
**System**: Mac OS X 10.11
**Thrown From**: [go-format](https://github.com/lsegal/atom-go-format) package, v1.0.7

### Stack Trace

Failed to load the go-format package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/admin/.atom/packages/go-format/lib/go-format-status-view.coffee:4:199)
    at /Users/admin/.atom/packages/go-format/lib/go-format-status-view.coffee:9:5
    at Object.<anonymous> (/Users/admin/.atom/packages/go-format/lib/go-format-status-view.coffee:41:5)
    at Object.<anonymous> (/Users/admin/.atom/packages/go-format/lib/go-format-status-view.coffee:43:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-snippets, v0.10.18
atom-django, v0.3.0
atom-html-preview, v0.1.11
go-format, v1.0.7
go-plus, v3.5.0
go-runtime, v0.2.0
grunt-runner, v0.11.0
gulp-snippets, v0.6.1
language-blade, v0.15.0
language-django, v0.1.1
language-python-django-templates, v0.1.0
laravel, v0.7.0
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Wrong repo. Try uninstalling go-format.
