### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by marpio** [joefitzgerald/go-plus#285]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of undefined

```
At /home/piotr/.atom/packages/go-plus/lib/executor.coffee:139

TypeError: Cannot read property 'stdin' of undefined
    at Executor.module.exports.Executor.exec (/home/piotr/.atom/packages/go-plus/lib/executor.coffee:139:39)
    at Executor.exec (/home/piotr/.atom/packages/go-plus/lib/executor.coffee:3:61)
    at Godef.module.exports.Godef.gotoDefinitionWithParameters (/home/piotr/.atom/packages/go-plus/lib/godef.coffee:144:37)
    at Godef.module.exports.Godef.gotoDefinitionForWordAtCursor (/home/piotr/.atom/packages/go-plus/lib/godef.coffee:96:19)
    at atom-workspace.Godef.atom.commands.add.golang:godef (/home/piotr/.atom/packages/go-plus/lib/godef.coffee:30:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:145:19)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
```

### Commands

```
     -0:00.7.0 golang:godef (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-coffee-script",
      "language-clojure",
      "language-objective-c",
      "language-perl",
      "language-php"
    ]
  },
  "go-plus": {
    "formatTool": "gofmt",
    "vetOnSave": false
  }
}
```

### Installed Packages

```coffee
# User
go-plus, v3.5.1

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`.
