### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-message-panel'

### ISSUE THREAD

**Issue by abduelhamit** [joefitzgerald/go-plus#286]
1. Update Atom
2. Update go-plus

**Atom Version**: 1.0.19
**System**: MRYEAH-PC
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.5.1

### Stack Trace

Uncaught Error: Cannot find module 'atom-message-panel'

```
At module.js:336

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Abdülhamit\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Abdülhamit\.atom\packages\go-plus\lib\dispatch.coffee:32:11)
    at Object.<anonymous> (C:\Users\Abdülhamit\.atom\packages\go-plus\lib\dispatch.coffee:791:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Abdülhamit\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "go-plus": {}
}
```

### Installed Packages

```coffee
# User
altgr, v0.1.0
build, v0.47.0
file-icons, v1.6.9
go-plus, v3.5.1
keyboard-localization, v1.4.8
symbols-tree-view, v0.10.0

# Dev
No dev packages
```

**Comment by abduelhamit** [comment]
Fixed it. Atom tried to find the file in `C:\Users\Abdﾃｼlhamit` instead of `C:\Users\Abdülhamit`.

The fix was easy:

    C:\Users>mklink /J Abdﾃｼlhamit Abdülhamit

**Comment by nexcode** [comment]
module.js:336

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Олег\.atom\packages\go-plus\lib\dispatch.coffee:14:57)
    at Object.<anonymous> (C:\Users\Олег\.atom\packages\go-plus\lib\dispatch.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
