### ISSUE TITLE
Uncaught SyntaxError: Unexpected token o

### ISSUE THREAD

**Issue by thypon** [joefitzgerald/go-plus#288]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: linux 4.1.9_1
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.5.1

### Stack Trace

Uncaught SyntaxError: Unexpected token o

```
At file:///usr/share/atom/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2Fhome%2Fgattuso%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.19%22%2C%22shellLoadTime%22%3A535%2C%22initialPaths%22%3A%5B%22%2Fhome%2Fgattuso%22%5D%7D:1

SyntaxError: Unexpected token o
    at Object.parse (native)
    at GocodeProvider.module.exports.GocodeProvider.mapMessages (/home/gattuso/.atom/packages/go-plus/lib/gocodeprovider.coffee:79:16)
    at done (/home/gattuso/.atom/packages/go-plus/lib/gocodeprovider.coffee:70:21)
    at exit (/home/gattuso/.atom/packages/go-plus/lib/executor.coffee:69:7)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)
```

### Commands

```
     -2:36.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:28 core:copy (atom-text-editor.editor.is-focused)
  2x -2:19.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:39 editor:newline (atom-text-editor.editor.is-focused)
     -1:09.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:08.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:56.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:55.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:53.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:48.8.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:46.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:31 application:new-file (atom-text-editor.editor.is-focused)
  2x -0:28 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
go-plus, v3.5.1

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`. JSON deserialization issues are now shown an error notification.
