### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-message-panel'

### ISSUE THREAD

**Issue by nexcode** [joefitzgerald/go-plus#291]
**Atom Version**: 1.0.19
**System**: Windows 10
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.5.1

### Stack Trace

Uncaught Error: Cannot find module 'atom-message-panel'

```
At module.js:336

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Олег\.atom\packages\go-plus\lib\dispatch.coffee:14:57)
    at Object.<anonymous> (C:\Users\Олег\.atom\packages\go-plus\lib\dispatch.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Олег\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "go-plus": {}
}
```

### Installed Packages

```coffee
# User
go-plus, v3.5.1
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Is this still an issue @nexcode?

**Comment by nexcode** [comment]
I rename user fonder. Now it contains only english characters.
