### ISSUE TITLE
Uncaught TypeError: go.godef is not a function

### ISSUE THREAD

**Issue by puneetguptanitj** [joefitzgerald/go-plus#295]
[Enter steps to reproduce below:]

1. pressed option + command + G

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.5.1

### Stack Trace

Uncaught TypeError: go.godef is not a function

```
At /Users/pg186025/.atom/packages/go-plus/lib/godef.coffee:78

TypeError: go.godef is not a function
    at Godef.module.exports.Godef.gotoDefinitionWithParameters (/Users/pg186025/.atom/packages/go-plus/lib/godef.coffee:78:14)
    at Godef.module.exports.Godef.gotoDefinitionForWordAtCursor (/Users/pg186025/.atom/packages/go-plus/lib/godef.coffee:62:6)
    at atom-workspace.Godef.atom.commands.add.golang:godef (/Users/pg186025/.atom/packages/go-plus/lib/godef.coffee:19:61)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/pg186025/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at /Users/pg186025/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/pg186025/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/pg186025/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/pg186025/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)
```

### Commands

```
     -1:06.5.0 application:add-project-folder (atom-text-editor.editor.is-focused)
  2x -0:45 golang:godef (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.10
go-plus, v3.5.1

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`.
