### ISSUE TITLE
Cmd click and be taken to package

### ISSUE THREAD

**Issue by brianvoe** [joefitzgerald/go-plus#320]
Im sure your aware that the sublime text version of go allows you to command click on a package or functions in a package and it will automatically take you to that package and function. This is great for developers as it allows you to understand what you are working with as quickly as possible.

Any chance of getting this integrated?

**Comment by kaskavalci** [comment]
+1
Plus, it would be better to have this go to definition on a small window as in Visual Studio.

**Comment by lloiser** [comment]
https://atom.io/packages/go-hyperclick (requires https://atom.io/packages/hyperclick)

**Comment by kaskavalci** [comment]
It seems hyperclick didn't work in my installation. Did you manage to run it @lloiser ?

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: 'navigator-godef' package, vundefined


### Stack Trace

Uncaught TypeError: this.goconfig is not a function

```
At /Users/i325753/.atom/packages/navigator-godef/lib/godef.js:144

TypeError: this.goconfig is not a function
    at Godef.gotoDefinitionWithParameters (/Users/i325753/.atom/packages/navigator-godef/lib/godef.js:144:25)
    at Object.callback (/Users/i325753/.atom/packages/go-hyperclick/lib/main.js:70:19)
    at HyperclickForTextEditor._confirmSuggestion (/Users/i325753/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:116:20)
    at HyperclickForTextEditor._onMouseDown (/Users/i325753/.atom/packages/hyperclick/lib/HyperclickForTextEditor.js:185:14)
```

### Commands

```
     -1:36.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:50.8.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -0:49.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:48.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:48.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:48.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:46.9.0 golang:godef (atom-text-editor.editor.is-focused)
     -0:44.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:41.5.0 core:cancel (a.stack-toggle)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
autocomplete-clang, v0.10.0 (active)
autocomplete-go, v1.2.0 (active)
autocomplete-python, v1.8.6 (active)
builder-go, v1.0.1 (active)
clang-format, v1.25.0 (active)
git-diff-details, v1.3.0 (active)
git-time-machine, v1.5.3 (inactive)
go-config, v1.2.4 (active)
go-debug, v0.1.22 (active)
go-get, v2.1.1 (active)
go-hyperclick, v1.1.0 (active)
go-outline, v0.6.0 (inactive)
go-plus, v4.3.2 (active)
go-signature-statusbar, v1.1.0 (active)
godoc, v1.1.0 (active)
gofmt, v1.2.0 (active)
gometalinter-linter, v1.2.2 (active)
gorename, v1.1.0 (active)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.39 (active)
language-cmake, v0.2.0 (active)
language-docker-erb, v0.1.0 (active)
language-protobuf, v0.7.0 (active)
language-restructuredtext, v1.0.0 (active)
language-scala, v1.1.6 (active)
linter, v1.11.18 (active)
linter-clang, v3.4.4 (active)
linter-gcc, v0.6.15 (active)
minimap-highlight-selected, v4.4.0 (active)
navigator-go, v1.1.3 (active)
open-terminal-here, v2.1.4 (inactive)
project-manager, v3.2.3 (active)
rst-preview, v1.3.1 (active)
split-diff, v1.0.4 (inactive)
tester-go, v2.0.2 (active)
tidy-markdown, v2.0.4 (active)
trailing-spaces, v0.3.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lloiser** [comment]
waiting for https://github.com/zheng1/go-hyperclick/pull/2

**Comment by zheng1** [comment]
Hi, go-hyperclick had upgrade. @brianvoe @kaskavalci , please upgrade to go-hyperclick@v1.1.2

**Comment by joefitzgerald** [comment]
This functionality is now included in go-plus and will be released in v5.0.0 on Monday December 19th.

**Comment by brianvoe** [comment]
Thanks

**Comment by Bdthomson** [comment]
Is there a way this can be disabled? This is overriding the current cmd-click in atom that supports multi cursor selection, and there is no apparent way to disable it currently in go-plus.

**Comment by zmb3** [comment]
Sure. Disable or uninstall the hyperclick package.

**Comment by Bdthomson** [comment]
I just rebound it to ctrl-click instead in hyperclick, did not realize it was even using the hyperclick package. Thanks for the quick response!

**Comment by joefitzgerald** [comment]
For what it is worth, when Hyperclick is using its default keybinding, `<kbd>cmd</kbd>-<kbd>option</kbd>-Click` is available for multi-cursor insertion.
