### ISSUE TITLE
Cannot read property 'isValidEditor' of null

### ISSUE THREAD

**Issue by jondal** [joefitzgerald/go-plus#353]
Hmm. What's going on here?

**Atom Version**: 1.5.0
**System**: Mac OS X 10.10.5
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package, v3.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'isValidEditor' of null

```
At /Users/x/.atom/packages/go-plus/lib/golint.coffee:41

TypeError: Cannot read property 'isValidEditor' of null
    at Golint.module.exports.Golint.checkCurrentBuffer (/Users/x/.atom/packages/go-plus/lib/golint.coffee:41:25)
    at atom-workspace.Golint.atom.commands.add.golang:golint (/Users/x/.atom/packages/go-plus/lib/golint.coffee:21:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
auto-detect-indentation, v0.4.2
autocomplete-ruby, v0.1.0
go-plus, v3.5.2
hex, v0.6.2
language-ruby-on-rails, v0.25.0
language-swift, v0.4.0
open-recent, v5.0.0
pretty-json, v0.4.1

**Comment by joefitzgerald** [comment]
Looks like you ran the menu command without an editor open. That shouldn't have caused an error, but I suppose there is a (current) expectation that a specific file is open.

In [gometalinter-linter](https://atom.io/packages/gometalinter-linter) I will add a command to lint an entire project or a directory in the tree view, but for now please just open a file before using the menu command.

**Comment by jondal** [comment]
I have a file open. :)

**Comment by joefitzgerald** [comment]
Hmph. OK. Things are still linting on save though, right?

**Comment by jondal** [comment]
Yeah, works on save. But I just found out it gets a bit weirder. I have a project open and it seems to fail in that case (if I run it manually), but does work if I open a single file in a new window. My project was opened automatically by Atom, since it was open when I quit Atom before. Not sure if that has anything to do with it?

Anyway, this isn't really bothering me. I just thought I should mention it.

**Comment by joefitzgerald** [comment]
Thanks for the info @jondal and sorry you're having issues! This is helpful info for https://github.com/joefitzgerald/gometalinter-linter/issues/7 and https://github.com/joefitzgerald/gometalinter-linter/issues/8.

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0`.
