### ISSUE TITLE
Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by ctessum** [joefitzgerald/go-plus#426]
I have been using go-plus for while (great work, by the way!) but it appears to have mostly stopped working for after the last update. It will still check for build errors after each save, and gofmt will work if I explicitly run it, but most of the other functionality seems to not work. For example, if I try to run godef with the chrome console open the following message will appear:

godef.js:130
TypeError: Cannot read property 'stdin' of undefined                             
    at /home/chris/.atom/packages/go-config/lib/executor.js:152:32
    at Executor.exec (/home/chris/.atom/packages/go-config/lib/executor.js:78:12)
    at /home/chris/.atom/packages/navigator-godef/lib/godef.js:120:30

System: Ubuntu 16.04
Atom version: 1.7.3
go-plus version: 4.1.0

**Comment by ctessum** [comment]
As an update, the problem appears to have spontaneously resolved itself. Never mind I guess!
