### ISSUE TITLE
Uncaught TypeError: Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by gaurav-chawla** [joefitzgerald/go-plus#564]
[Enter steps to reproduce:]

1. ... upgraded to latest go-plus package.

**Atom**: 1.14.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package 5.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'localeCompare' of undefined

```
At /Users/xxx/.atom/packages/go-plus/lib/panel/go-plus-panel.js:102

TypeError: Cannot read property 'localeCompare' of undefined
    at /packages/go-plus/lib/panel/go-plus-panel.js:102:50
    at Array.sort (native)
    at GoPlusPanel.render (/packages/go-plus/lib/panel/go-plus-panel.js:102:8)
    at Object.initialize (/packages/go-plus/node_modules/etch/dist/component-helpers.js:60:34)
    at GoPlusPanel.EtchComponent (/packages/go-plus/lib/etch-component.js:14:10)
    at /packages/go-plus/lib/panel/go-plus-panel.js:11:33)
    at PanelManager.refreshPanel (/packages/go-plus/lib/panel/panel-manager.js:48:24)
    at PanelManager.setActivated (/packages/go-plus/lib/panel/panel-manager.js:30:10)
    at Object.showPanel (/packages/go-plus/lib/main.js:266:30)
    at Bootstrap.onActivated (/packages/go-plus/lib/main.js:29:12)
    at Bootstrap.check (/packages/go-plus/lib/bootstrap.js:91:14)
    at Bootstrap.setGrammarUsed (/packages/go-plus/lib/bootstrap.js:74:10)
    at /packages/go-plus/lib/bootstrap.js:58:12
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (/app.asar/src/package-manager.js:594:43)
    at Workspace.module.exports.Workspace.handleGrammarUsed (/app.asar/src/workspace.js:618:34)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.handleGrammarChange (/app.asar/src/text-editor.js:3260:27)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/app.asar/src/tokenized-buffer.js:122:27)
    at TextEditor.module.exports.TextEditor.setGrammar (/app.asar/src/text-editor.js:2836:35)
    at TextEditorRegistry.setGrammarOverride (/app.asar/src/text-editor-registry.js:274:14)
    at GrammarListView.module.exports.GrammarListView.confirmed (/app.asar/node_modules/grammar-selector/lib/grammar-list-view.js:59:28)
    at GrammarListView.module.exports.SelectListView.confirmSelection (/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at /app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:21.2.0 grammar-selector:show (atom-text-editor.editor)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-python-package 0.7.0 
autocomplete-go 1.3.0 
autocomplete-java 1.2.5 
autocomplete-python 1.8.43 
build-gradle 0.6.0 
builder-go 1.0.1 
go-config 1.2.4 
go-debug 1.0.4 
go-get 2.1.1 
go-imports 0.1.1 
go-plus 5.1.1 
godoc 1.1.1 
gofmt 1.2.0 
gometalinter-linter 1.2.2 
gorename 1.1.0 
java-importer 1.4.1 
language-gradle 0.0.3 
language-groovy 0.6.0 
linter 1.11.21 
linter-python-pep8 0.2.0 
MagicPython 1.0.6 
navigator-go 1.1.3 
node-debugger 1.10.0 
python-indent 1.0.0 
python-iresolve 0.0.3 
python-tools 0.6.9 
python-yapf 0.13.0 
Quick-JavaScript 2.2.0 
tester-go 2.0.2 
```

**Comment by moorage** [comment]
This just happened for me on a Mac with Atom 1.22.0

**Comment by jhjames3** [comment]
this just happened to me on a Mac with Atom 1.26.1

**Comment by jhjames3** [comment]
and again with Atom 1.31.2x64
