### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, uv_chdir

### ISSUE THREAD

**Issue by lm913** [joefitzgerald/go-plus#584]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package 5.2.0

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, uv_chdir

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/decompress-zip/node_modules/graceful-fs/polyfills.js:14

Error: ENOTDIR: not a directory, uv_chdir
    at Error (native)
    at process.chdir (/app.asar/node_modules/decompress-zip/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/packages/go-plus/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/packages/go-debug/node_modules/graceful-fs/polyfills.js:21:9)
    at lint (/packages/jshint/index.js:229:10)
    at complete (/app.asar/node_modules/lodash/index.js:7697:25)
    at delayed (/app.asar/node_modules/lodash/index.js:7707:11)
```

### Commands

```
     -0:40.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-atom-material-syntax.theme-atom-material-ui)
     -0:20.2.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-atom-material-syntax.theme-atom-material-ui.has-custom-icons)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-easy-jsdoc 4.10.0 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-minify 0.8.0 
autoclose-html 0.23.0 
dash 1.7.1 
environment 1.3.1 
eval-javascript 1.2.0 
external-open 0.6.3 
file-icons 2.0.16 
go-debug 1.0.4 
go-plus 5.2.0 
go-signature-statusbar 1.2.0 
godef 0.2.5 
hex 0.6.2 
highlight-selected 0.12.0 
hyperclick 0.0.40 
jsdoc-generator 0.2.3 
jshint 1.8.6 
language-docker 1.1.7 
language-protobuf 0.7.1 
linter 1.11.23 
mac-fix-path 0.0.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-pigments 0.2.2 
pigments 0.39.0 
platformio-ide-terminal 2.3.1 
script 3.14.1 
tabularize 0.2.5 
```

**Comment by joefitzgerald** [comment]
I experienced this today when I installed go-plus in atom on a fresh windows VM. I didn't have `git` installed yet, and I had to ensure it was on my path before the installation would work correctly.
