### ISSUE TITLE
Uncaught TypeError: Cannot read property 'unshift' of undefined

### ISSUE THREAD

**Issue by nkovacs** [joefitzgerald/go-plus#592]
[Enter steps to reproduce:]

1. Created a new file named "main.go" in an empty directory
2. Started typing "package main"

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package 5.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'unshift' of undefined

```
At /home/nkovacs/.atom/packages/go-plus/lib/what/what.js:85

TypeError: Cannot read property 'unshift' of undefined
    at What.run (/packages/go-plus/lib/what/what.js:85:11)
    at /packages/go-plus/lib/what/what.js:41:14
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/app.asar/src/text-editor.js:2087:27)
    at Selection.module.exports.Selection.markerDidChange (/app.asar/src/selection.js:921:21)
    at /app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/app.asar/node_modules/text-buffer/lib/marker.js:421:20)
    at /app.asar/node_modules/text-buffer/lib/marker-layer.js:312:25
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/app.asar/node_modules/text-buffer/lib/marker-layer.js:309:39)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1334:34)
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:843:12)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1551:26)
    at /app.asar/src/text-editor.js:1128:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2528:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:2490:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1126:19)
    at TextEditor.module.exports.TextEditor.insertText (/app.asar/src/text-editor.js:1092:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/app.asar/src/text-editor-component.js:478:26)
    at /app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
     -0:12.5.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:10.5.0 core:confirm (input.hidden-input)
     -0:10.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.0 
atom-jade 0.3.0 
buffer-pos 0.3.0 
editorconfig 2.2.2 
git-blame 0.4.11 
git-history 3.2.0 
go-debug 1.1.0 
go-oracle 0.2.1 
go-plus 5.3.0 
go-rename 0.3.0 
go-signature-statusbar 1.2.0 
highlight-selected 0.12.0 
hyperclick 0.0.40 
language-pug 0.0.21 
language-vue 0.21.2 
linter 1.11.23 
merge-conflicts 1.4.4 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-selection 4.4.0 
release-notes 0.53.0 
sort-lines 0.14.0 
split-diff 1.2.0 
sync-settings 0.8.1 
synced-sidebar 0.4.3 
tab-control 0.6.9 
```

**Comment by joefitzgerald** [comment]
Sorry about this! Fixed in https://github.com/joefitzgerald/go-plus/commit/48cd1ea07f67a6c4ac3760b5204e546d368ba1ed.

**Comment by nkovacs** [comment]
Thanks
