### ISSUE TITLE
Uncaught Error: Invalid child node: undefined

### ISSUE THREAD

**Issue by kristiehoward** [joefitzgerald/go-plus#657]
[Enter steps to reproduce:]

1. Replace All on .go files

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package 5.5.5

### Stack Trace

Uncaught Error: Invalid child node: undefined

```
At /Users/kristiehoward/.atom/packages/go-plus/node_modules/etch/lib/dom.js:25

Error: Invalid child node: undefined
    at Object.dom (/packages/go-plus/node_modules/etch/lib/dom.js:25:15)
    at /packages/go-plus/lib/panel/go-plus-panel.js:119:144
    at Array.map (native)
    at GoPlusPanel.render (/packages/go-plus/lib/panel/go-plus-panel.js:117:19)
    at updateSync (/packages/go-plus/node_modules/etch/lib/component-helpers.js:99:34)
    at /packages/go-plus/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:223:1)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:1
```

### Commands

```
     -0:34.9.0 project-find:show (input.hidden-input)
     -0:30.3.0 core:confirm (input.hidden-input)
     -0:28.7.0 core:copy (input.hidden-input)
     -0:27.9.0 core:paste (input.hidden-input)
 12x -0:27.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
api-blueprint-preview 0.7.0 
atom-tag-wrapper 0.2.0 
autocomplete-go 1.1.0 
builder-go 1.0.0 
busy-signal 1.4.1 
duplicate-removal 0.1.3 
fast-eslint 3.13.0 
file-icons 2.1.6 
go-config 1.2.4 
go-debug 1.4.2 
go-get 2.1.1 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
godoc 1.1.1 
gofmt 1.1.6 
gometalinter-linter 1.1.0 
gorename 1.0.2 
hyperclick 0.0.40 
intentions 1.1.2 
language-api-blueprint 1.0.2 
language-docker 1.1.8 
linter 2.1.4 
linter-eslint 8.2.1 
linter-stylelint 3.10.0 
linter-ui-default 1.6.0 
motepair 0.24.0 
navigator-go 1.1.3 
pigments 0.39.1 
react 0.16.2 
sort-lines 0.14.0 
tester-go 1.0.4 
todo-show 1.11.0 
```

**Comment by zmb3** [comment]
This may or may not be related to your problem, but I noticed you have a bunch of old packages installed.  The following packages should be removed as they're functionality is implemented in Go-Plus 5.0+:

- tester-go
- gorename
- gofmt
- godoc
- go-get
- go-config
- builder-go

**Comment by kristiehoward** [comment]
@zmb3 I did remove those old packages, reinstalled go plus, but was still having the issue. Recently switched to VS Code though so I'm not having the issue any more, so we can close it 😄

**Comment by kristiehoward** [comment]
(not sure if I am supposed to close it or you are)
