### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by HT808s** [joefitzgerald/go-plus#697]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package 5.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /home/jernewein/.atom/packages/go-plus/lib/usage/usage.js:102

TypeError: Cannot read property 'then' of undefined
    at Usage.updateContent (/packages/go-plus/lib/usage/usage.js:102:26)
    at Usage.exec (/packages/go-plus/lib/usage/usage.js:114:10)
    at HTMLElement.golangFindUsage (/packages/go-plus/lib/usage/usage.js:35:16)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:324:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  3x -0:42.9.0 window:increase-font-size (input.hidden-input)
     -0:39.3.0 intentions:highlight (input.hidden-input)
     -0:39.1.0 find-and-replace:show (input.hidden-input)
  6x -0:35.2.0 core:backspace (input.hidden-input)
  3x -0:33 core:confirm (input.hidden-input)
     -0:28.9.0 editor:consolidate-selections (input.hidden-input)
     -0:28.9.0 core:cancel (input.hidden-input)
     -0:28.5.0 core:move-right (input.hidden-input)
     -0:28.1.0 intentions:highlight (input.hidden-input)
     -0:27.7.0 command-palette:toggle (input.hidden-input)
     -0:25.8.0 core:confirm (input.hidden-input)
     -0:25.8.0 golang:find-usage (input.hidden-input)
     -0:12.1.0 intentions:highlight (input.hidden-input)
     -0:11.6.0 key-binding-resolver:toggle (input.hidden-input)
     -0:09.3.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
     -0:08.7.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
go-debug 1.5.2 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.8 
multi-cursor-increment 0.1.1 
prettier-atom 0.40.0 
```

**Comment by dvsekhvalnov** [comment]
Hey, was it fixed? Facing it with atom 1.22.1 and go-plus 5.6.0?

**Comment by joefitzgerald** [comment]
We haven't released a new version of `go-plus` since then (https://github.com/joefitzgerald/go-plus/releases); it is fixed on `master`. We'll get a new release out shortly.

**Comment by dvsekhvalnov** [comment]
Thanks for update !
