### ISSUE TITLE
Uncaught TypeError: Promise.resovle is not a function

### ISSUE THREAD

**Issue by AmrAlfoly** [joefitzgerald/go-plus#701]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package 5.6.0

### Stack Trace

Uncaught TypeError: Promise.resovle is not a function

```
At /home/amr/.atom/packages/go-plus/lib/panel/panel-manager.js:142

TypeError: Promise.resovle is not a function
    at PanelManager.togglePanel (/packages/go-plus/lib/panel/panel-manager.js:142:24)
    at OutputManager.model.requestFocus (/packages/go-plus/lib/panel/panel-manager.js:99:19)
    at OutputManager.update (/packages/go-plus/lib/output-manager.js:22:14)
    at /packages/go-plus/lib/get/get-manager.js:19:25)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:11.8.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:32.2.0 core:save (input.hidden-input)
     -8:28.9.0 settings-view:open (input.hidden-input)
     -8:13.1.0 core:confirm (input.hidden-input)
     -7:01.3.0 core:paste (input.hidden-input)
     -7:00.4.0 core:confirm (input.hidden-input)
 25x -6:22.6.0 core:backspace (input.hidden-input)
  2x -6:20.2.0 core:confirm (input.hidden-input)
     -0:20.2.0 golang:update-tools (atom-pane.pane.active)
```

### Non-Core Packages

```
busy-signal 1.4.3 
go-debug 1.5.2 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
```

**Comment by zmb3** [comment]
Well that’s a terrible mistake 😬. Will get a fix out asap
