### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by stevanus1997** [joefitzgerald/go-plus#713]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Education
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package 5.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of null

```
At C:\Users\Stevanus\.atom\packages\go-plus\lib\panel\go-plus-panel.js:45

TypeError: Cannot read property 'forEach' of null
    at GoPlusPanel.render (/packages/go-plus/lib/panel/go-plus-panel.js:45:35)
    at updateSync (/packages/go-plus/node_modules/etch/lib/component-helpers.js:107:34)
    at /packages/go-plus/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/app.asar/src/view-registry.js:187:9)
    at /app.asar/src/view-registry.js:3:59
```

### Commands

```
 14x -1:53.8.0 core:move-down (input.hidden-input)
     -1:39 intentions:highlight (input.hidden-input)
     -1:38.9.0 core:save (input.hidden-input)
     -0:22.2.0 intentions:highlight (input.hidden-input)
     -0:22 core:undo (input.hidden-input)
     -0:19.5.0 intentions:highlight (input.hidden-input)
     -0:19.4.0 core:save (input.hidden-input)
     -0:18.6.0 intentions:highlight (input.hidden-input)
  2x -0:18.5.0 core:save (input.hidden-input)
     -0:17.8.0 core:undo (input.hidden-input)
     -0:17 core:save (input.hidden-input)
     -0:12.9.0 intentions:highlight (input.hidden-input)
     -0:12.8.0 core:undo (input.hidden-input)
     -0:09.8.0 core:backspace (input.hidden-input)
     -0:09.7.0 intentions:highlight (input.hidden-input)
     -0:09.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-laravel-snippets 0.2.0 
atom-react-instyle 0.2.8 
atom-react-native-style 0.1.5 
atom-react-snippets 0.2.2 
atom-ternjs 0.18.3 
badass-react-snippets 1.1.0 
busy-signal 1.4.3 
docblockr 0.11.0 
duplicate-line-or-selection 0.9.0 
expand-region 0.3.2 
file-icons 2.1.13 
git-control 0.9.0 
git-plus 7.10.0 
git-time-machine 1.5.9 
go-debug 1.5.2 
go-imports 0.1.1 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-shorcuts-react 2.1.0 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.11.1 
language-babel 2.75.1 
language-blade 0.36.0 
language-patch 1.2.0 
laravel 0.7.1 
laravel-4-snippets 0.1.0 
laravel-5-snippets 0.8.0 
laravel-eloquent-snippets 2.0.0 
laravel-forms-bootstrap-snippets 1.2.0 
laravel-helper 0.2.1 
laravel-snippets 2.1.0 
linter 2.2.0 
linter-eslint 8.3.2 
linter-ui-default 1.6.10 
local-history 4.3.0 
markdown-preview-plus 2.4.10 
merge-conflicts 1.4.5 
modern-react-snippets 0.3.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-plus 1.0.0 
re-re-re-react 3.0.0 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
react-generatr 1.0.0 
react-native-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-redux-es6-snippets 0.1.3 
react-redux-react-native-snippets 0.2.4 
react-snippets 1.0.0 
react-storybook-snippets 0.3.0 
split-diff 1.5.1 
todo-show 2.1.0 
xatom-debug 1.6.11 
xatom-debug-chrome 0.7.4 
xatom-debug-nodejs 0.9.3 
```

**Comment by zmb3** [comment]
This should be fixed with the next release.
