### ISSUE TITLE
Failed to load the go-plus package

### ISSUE THREAD

**Issue by rshphx** [joefitzgerald/go-plus#715]
[Enter steps to reproduce:]

I did nothing more than just upgrade the package when asked. When Atom restarted, got that error message.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [go-plus](https://github.com/joefitzgerald/go-plus) package 5.6.0

### Stack Trace

Failed to load the go-plus package

```
At UNKNOWN: unknown error, open 'C:\Users\...\.atom\compile-cache\less\49b8dcc566b4fbee38a9fb47e7b24b5dd27e3f89\content\b6f8b7d797b0e81f4507f6bf73ff9579ad668409\overrides.json'

Error: UNKNOWN: unknown error, open 'C:\Users\...\.atom\compile-cache\less\49b8dcc566b4fbee38a9fb47e7b24b5dd27e3f89\content\b6f8b7d797b0e81f4507f6bf73ff9579ad668409\overrides.json'
  at Object.fs.openSync (fs.js:558:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
  at Object.fs.writeFileSync (fs.js:1233:33)
  at Proxy.writeFileSync (<embedded>:17433:29)
  at LessCache.module.exports.LessCache.writeJson (<embedded>:129817:23)
  at LessCache.module.exports.LessCache.putCachedCss (<embedded>:129905:18)
  at LessCache.module.exports.LessCache.cssForFile (<embedded>:129963:18)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (<embedded>:72311:31)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (<embedded>:24627:39)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (<embedded>:24596:27)
  at <embedded>:71092:60
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (<embedded>:71090:65)
  at <embedded>:70698:25
  at Package.module.exports.Package.measure (<embedded>:70646:21)
  at Package.module.exports.Package.load (<embedded>:70691:18)
  at PackageManager.loadAvailablePackage (<embedded>:24067:16)
  at config.transact (<embedded>:23980:20)
  at Config.module.exports.Config.transact (<embedded>:20985:22)
  at PackageManager.loadPackages (<embedded>:23978:23)
  at <embedded>:1059:34

```

### Commands

```
     -3:04.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angularjs 0.4.0 
atom-angular-material-snippets 1.3.0 
atom-beautify 0.30.9 
atom-jade 0.3.0 
atom-mermaid 3.2.1 
autocomplete-angular-material 0.4.0 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.14 
git-control 0.9.0 
git-time-machine 1.5.9 
go-plus 5.6.0 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
node-debugger 1.10.1 
spacegray-atom-dark-syntax 1.3.2 
spacegray-dark-ui 0.13.0 
```

**Comment by zmb3** [comment]
The stack trace doesn't show any go-plus code even running yet.  It looks like the upgrade just went bad.  I would try uninstalling and reinstalling go-plus.
