### ISSUE TITLE
Failed to activate the go-plus package

### ISSUE THREAD

**Issue by LouisParkin** [joefitzgerald/go-plus#741]
### Prerequisites

* [Yes ] Have you tried launching `atom .` from the terminal in your project's directory?
* [Yes ] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [Yes ] Have you updated Atom to the latest version?
* [No ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [Yes ] Have you updated your Atom packages to the latest versions?
* [No ] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [Yes ] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description
![screenshot from 2018-01-22 09-35-03](https://user-images.githubusercontent.com/11991882/35209613-8d3c1cf2-ff57-11e7-8958-9eb7e2a9b9c8.png)

go-plus fails to load

### Output from `atom -v && apm -v`

$ atom -v
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ atom -v
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Output From `go env`

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/louis/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build992384452=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### Steps to Reproduce

1. Open Atom
2. Wait for big red error box to appear on right-hand side.
3 See stack trace:

```
SyntaxError: Unexpected token (
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/louis/.atom/packages/go-plus/lib/orchestrator.js:4:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/home/louis/.atom/packages/go-plus/lib/main.js:37:28)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:1014:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/usr/share/atom/resources/app/src/package-manager.js:676:42)
    at /usr/share/atom/resources/app/src/package-manager.js:607:23
```

### Expected Behavior

No red error box.
go-plus features must be available.

### Actual Behavior

go-plus doesn't load, is not available to use while coding in atom.

**Comment by joefitzgerald** [comment]
Please update your atom version. You are running 1.18.x, while stable (https://atom.io) is currently 1.23.x and beta (https://atom.io/beta) is `1.24.x`.

**Comment by LouisParkin** [comment]
That resolved the issue, thanks.

**Comment by jonomcclelland** [comment]
I'm still having this issue. 

`
Error: Cannot find module 'atom-babel6-transpiler' from '/Users/.../.atom/packages/go-plus'
    at Function.module.exports [as sync] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/resolve/lib/sync.js:40:15)
    at PackageTranspilationRegistry.getTranspilerPath (/Applications/Atom.app/Contents/Resources/app/src/package-transpilation-registry.js:180:26)
    at PackageTranspilationRegistry.getCachePath (/Applications/Atom.app/Contents/Resources/app/src/package-transpilation-registry.js:131:39)
    at Object.getCachePath (/Applications/Atom.app/Contents/Resources/app/src/package-transpilation-registry.js:67:29)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:91:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:238:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/src/package.js:901:81)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:717:40)
    at Promise.all.then (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:650:18)`

On these versions:

`$ atom -v
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm -v
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.10
git 2.15.0`


Tried installing the missing **atom-babel6-transpiler** module. That installs and works OK without goplus, but with goplus also installed, I get the above error. Any ideas?
