### ISSUE TITLE
Failed to install the go-plus package

### ISSUE THREAD

**Issue by mengjieli0726** [joefitzgerald/go-plus#821]
my atom version is 1.14. when I  install the go-hyperclick 1.1.2 , the below error throw:

```
SyntaxError: Unexpected token (
    at Module._compile (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:79:40)
    at Object.value [as .js] (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/mjli/.atom/packages/go-plus/lib/orchestrator.js:4:1)
    at Module._compile (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/Users/mjli/.atom/packages/go-plus/lib/main.js:37:28)
    at Package.module.exports.Package.activateNow (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/package.js:218:19)
    at /private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/package.js:922:28
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/package-manager.js:563:50
    at Set.forEach (native)
    at PackageManager.module.exports.PackageManager.activatePackage (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/package-manager.js:561:41)
    at /private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:69:16)
    at triggerExitCallback (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:303:11)
    at ChildProcess.<anonymous> (/private/var/folders/pq/7h22vd316y9ggkm00fqrs1t40000gn/T/AppTranslocation/31CD6BF2-A7F9-4A80-BCFD-A85FCA8B27CB/d/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:333:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by zmb3** [comment]
Atom 1.14 is very old - have you considered updating to the latest version?

Also, go-hyperclick is no longer necessary.  It's functionality has been merged into go-plus.
