### ISSUE TITLE
Cannot find module './clone.js', Failed to activate the go-plus package

### ISSUE THREAD

**Issue by andrewmilson** [joefitzgerald/go-plus#825]
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you updated Atom to the latest version?
* [x] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Getting this error on atom startup

```
Failed to activate the go-plus package
Cannot find module './clone.js'
```

Stacktrace:
```Error: Cannot find module './clone.js'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154368)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145675)
    at Object.<anonymous> (/home/andrew/.atom/packages/go-plus/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Object.<anonymous> (/home/andrew/.atom/packages/go-plus/node_modules/graceful-fs/graceful-fs.js:281:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145675)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/github/node_modules/fs-extra/lib/fs/index.js:4:12)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/github/node_modules/fs-extra/lib/fs/index.js:109:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145675)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/github/node_modules/fs-extra/lib/index.js:8:12)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/github/node_modules/fs-extra/lib/index.js:24:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145675)
    at Object.<anonymous> (/home/andrew/.atom/packages/go-plus/lib/config/executor.js:6:1)
    at Object.<anonymous> (/home/andrew/.atom/packages/go-plus/lib/config/executor.js:216:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145675)
    at Object.<anonymous> (/home/andrew/.atom/packages/go-plus/lib/config/service.js:4:1)
    at Object.<anonymous> (/home/andrew/.atom/packages/go-plus/lib/config/service.js:57:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145675)
    at Object.provideGoConfig (/home/andrew/.atom/packages/go-plus/lib/main.js:406:29)
    at Object.loadInformation (/home/andrew/.atom/packages/go-plus/lib/main.js:122:45)
    at Object.load (/home/andrew/.atom/packages/go-plus/lib/main.js:89:10)
    at Bootstrap.bootstrap.Bootstrap [as onActivated] (/home/andrew/.atom/packages/go-plus/lib/main.js:44:12)
    at Bootstrap.check (/home/andrew/.atom/packages/go-plus/lib/bootstrap.js:99:14)
    at Bootstrap.setGrammarUsed (/home/andrew/.atom/packages/go-plus/lib/bootstrap.js:82:10)
    at subscriptions.add.atom.workspace.observeTextEditors.editor (/home/andrew/.atom/packages/go-plus/lib/bootstrap.js:70:14)
    at Workspace.observeTextEditors (/usr/share/atom/resources/app/static/<embedded>:11:425358)
    at Bootstrap.subscribeToEvents (/home/andrew/.atom/packages/go-plus/lib/bootstrap.js:68:43)
    at new Bootstrap (/home/andrew/.atom/packages/go-plus/lib/bootstrap.js:39:10)
    at Object.activate (/home/andrew/.atom/packages/go-plus/lib/main.js:42:22)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:2904922)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/usr/share/atom/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1186142)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1187583)
    at PackageManager.triggerDeferredActivationHooks (/usr/share/atom/resources/app/static/<embedded>:11:380394)
    at Promise.all.then (/usr/share/atom/resources/app/static/<embedded>:11:379192)
    at <anonymous>
```

### Output from `atom -v && apm -v`

Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.12
git 2.7.4

### Output From `go env`

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/andrew/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/andrew/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build458447353=/tmp/go-build -gno-record-gcc-switches"

**Comment by zmb3** [comment]
Seems this is related to our dependency on fs-extra: 

https://github.com/jprichardson/node-fs-extra/issues/645
https://github.com/isaacs/node-graceful-fs/commit/a1587eae7c5dcf74ccf6556ac7d6f704ea794804

Looks like the issue was fixed upstream, so a reinstall should work.
