### ISSUE TITLE
Cannot find module 'atom-babel6-transpiler' from...

### ISSUE THREAD

**Issue by whyliyu** [joefitzgerald/go-plus#846]
### Output from atom -v && apm -v
Atom : 1.33.1
Electron: 2.0.16
Chrome : 61.0.3163.100
Node : 8.9.3

### Output From go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\liyuhang1\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\goworkspace
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessag                                                                                                                                                                                               e-length=0 -fdebug-prefix-map=C:\Users\liyuhang1\AppData\Local\Temp\go-build9789                                                                                                                                                                                               25602=/tmp/go-build -gno-record-gcc-switches

### Steps to Reproduce
1.open ATOM
2.you will see a red alert box on the right, titled "Failed to activate the go-plus package".

### Stack Trace
Cannot find module 'atom-babel6-transpiler' from 'C:\Users\liyuhang1\.atom\packages\go-plus'
Error: `Cannot find module 'atom-babel6-transpiler' from 'C:\Users\liyuhang1\.atom\packages\go-plus'
Hide Stack Trace
Error: Cannot find module 'atom-babel6-transpiler' from 'C:\Users\liyuhang1\.atom\packages\go-plus'
    at Function.module.exports [as sync] (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app.asar\node_modules\resolve\lib\sync.js:43:15)
    at PackageTranspilationRegistry.getTranspilerPath (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:575432)
    at PackageTranspilationRegistry.getCachePath (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:574387)
    at Object.getCachePath (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:573474)
    at compileFileAtPath (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:147616)
    at Object.value [as .js] (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150197)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/liyuhang1/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:1:639369)
    at Package.requireMainModule (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:3041061)
    at Package.activateNow (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:3029195)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:14:2445)
    at Function.simpleDispatch (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:1190759)
    at Emitter.emit (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:1192200)
    at PackageManager.triggerDeferredActivationHooks (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:383101)
    at Promise.all.then (C:\Users\liyuhang1\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:381899)
    at <anonymous>`

###Actual Behavior
go-plus doesn't load, is not available to use while coding in atom.

**Comment by whyliyu** [comment]
just run "$ apm install" in its directory to install go-plus
